export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_RECEIVE = 'PRODUCT_RECEIVE'
//export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE'
// export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE'

export const MORE_PRODUCTS_REQUEST = 'MORE_PRODUCTS_REQUEST'
export const MORE_PRODUCTS_RECEIVE = 'MORE_PRODUCTS_RECEIVE'
// export const MORE_PRODUCTS_FAILURE = 'MORE_PRODUCTS_FAILURE'

export const PAGE_REQUEST = 'PAGE_REQUEST'
export const PAGE_RECEIVE = 'PAGE_RECEIVE'
// export const PAGE_FAILURE = 'PAGE_FAILURE'

export const CART_REQUEST = 'CART_REQUEST'
export const CART_RECEIVE = 'CART_RECEIVE'
// export const CART_FAILURE = 'CART_FAILURE'

export const CART_ITEM_ADD_REQUEST = 'CART_ITEM_ADD_REQUEST'
// export const CART_ITEM_ADD_RECEIVE = 'CART_ITEM_ADD_RECEIVE'
// export const CART_ITEM_ADD_FAILURE = 'CART_ITEM_ADD_FAILURE'

export const CART_ITEM_DELETE_REQUEST = 'CART_ITEM_DELETE_REQUEST'
// export const CART_ITEM_DELETE_RECEIVE = 'CART_ITEM_DELETE_RECEIVE'
// export const CART_ITEM_DELETE_FAILURE = 'CART_ITEM_DELETE_FAILURE'

export const CART_ITEM_UPDATE_REQUEST = 'CART_ITEM_UPDATE_REQUEST'
// export const CART_ITEM_UPDATE_RECEIVE = 'CART_ITEM_UPDATE_RECEIVE'
// export const CART_ITEM_UPDATE_FAILURE = 'CART_ITEM_UPDATE_FAILURE'

export const SHIPPING_METHODS_REQUEST = 'SHIPPING_METHODS_REQUEST'
export const SHIPPING_METHODS_RECEIVE = 'SHIPPING_METHODS_RECEIVE'
// export const SHIPPING_METHODS_FAILURE = 'SHIPPING_METHODS_FAILURE'

export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST'
export const PAYMENT_METHODS_RECEIVE = 'PAYMENT_METHODS_RECEIVE'
// export const PAYMENT_METHODS_FAILURE = 'PAYMENT_METHODS_FAILURE'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_RECEIVE = 'CHECKOUT_RECEIVE'
// export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const SITEMAP_REQUEST = 'SITEMAP_REQUEST'
export const SITEMAP_RECEIVE = 'SITEMAP_RECEIVE'
// export const SITEMAP_FAILURE = 'SITEMAP_FAILURE'

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER'

export const LOCATION_CHANGED = 'LOCATION_CHANGED'

export const UPDATE_PRICE = 'UPDATE_PRICE'

export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";
export const USER_LOGIN_FULFILLED = "USER_LOGIN_FULFILLED";
export const USER_LOGIN_REJECTED = "USER_LOGIN_REJECTED";

export const USER_UPDATE_STARTED = "USER_UPDATE_STARTED";
export const USER_UPDATE_FULFILLED = "USER_UPDATE_FULFILLED";
export const USER_UPDATE_REJECTED = "USER_UPDATE_REJECTED";

export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const GET_TOKEN_USER = "GET_TOKEN_USER";
export const FILL_ORDERS = "FILL_ORDERS";
export const FILL_ADDRESSES = "FILL_ADDRESSES";
export const FILL_USER = "FILL_USER";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
